title: Rafael Audibert's Blog
email: rbaudibert@inf.ufrgs.br
description: > # this means to ignore newlines until "baseurl:"
  My name is Rafael Baldasso Audibert, and I'm a 19 years old
  CS Bsc. Student @ UFRGS, Brazil. Here I will write some random stuff,
  that I hope you will enjoy reading as much as enjoy writing it.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://inf.ufrgs.br/~rbaudibert" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Rafael Audibert # add your name
author-pic: photo.jpg
about-author: >
  My name is Rafael Baldasso Audibert, and I'm a 19 years old
  CS Bsc. Student @ UFRGS, Brazil. Here I will write some random stuff,
  that I hope you will enjoy reading as much as enjoy writing it.

# Contact links
email: rbaudibert@inf.ufrgs.br
phone: +55 (54) 99645-5959
website: inf.ufrgs.br/~rbaudibert
linkedin: rbaudibert
github: rafaeelaudibert
facebook: rbaudibert
twitter: rbaudibert
instagram: '@rafaaudibeert'
pinterest: rafaeelaudibert

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: rbaudibert # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins_dir:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
